/*
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */
package org.mule.runtime.extension.api.error;

import static org.mule.metadata.api.builder.BaseTypeBuilder.create;

import org.mule.metadata.api.model.MetadataFormat;
import org.mule.metadata.api.model.MetadataType;

/**
 * Provides useful static values fir use in extensions declarers dealing with error types.
 * 
 * @since 1.4
 */
public final class ErrorConstants {

  private ErrorConstants() {
    // Nothing to do
  }

  /**
   * Parameters of this type declare new error types specific to the artifact that declares in.
   */
  public static final MetadataType ERROR_TYPE_DECLARED = create(new MetadataFormat("Text", "text", "text/plain"))
      .stringType()
      .id("errorTypeDeclared")
      .enumOf("ANY", "REDELIVERY_EXHAUSTED", "TRANSFORMATION", "EXPRESSION", "SECURITY", "CLIENT_SECURITY",
              "SERVER_SECURITY", "ROUTING", "CONNECTIVITY", "RETRY_EXHAUSTED", "TIMEOUT")
      .build();

  /**
   * Parameters of this type declare a matcher for error types that can be generated by the application.
   */
  public static final MetadataType ERROR_TYPE_MATCHER = create(new MetadataFormat("Text", "text", "text/plain"))
      .stringType()
      .id("errorTypeMatcher")
      .build();

}
